language: go

go: 
        - 1.10.x

os:
        - linux

sudo: false

script:
        - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
        - bash <(curl -s https://codecov.io/bash)
