language: go

go: 
        - tip
        - 1.8.x
        - 1.7.x
        - 1.6.x

os:
        - linux
        - osx

sudo: false

script:
        - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
        - bash <(curl -s https://codecov.io/bash)
